# Generated by Django 4.2 on 2023-04-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Callboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Callboardapp.call'),
            preserve_default=False,
        ),
    ]
