# Generated by Django 4.2 on 2023-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Callboardapp', '0002_response_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидает ответа'), ('ACCEPTED', 'Принят'), ('DENIED', 'Отклонен')], default='WAITING', max_length=10),
        ),
    ]
