# Generated by Django 4.2 on 2023-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Callboardapp', '0003_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Ожидает ответа'), ('ACCEPTED', 'Принят')], default='WAITING', max_length=10),
        ),
    ]
