# Generated by Django 4.2 on 2023-05-01 20:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Callboardapp', '0004_alter_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
